import { expect, test } from '@playwright/test';

// TODO: These tests need to be rewritten to match the current employee interface
// The current interface uses different form fields and buttons
test.describe.skip('AI Schedule Generation', () => {
  test('should generate schedule with AI successfully', async ({ page }) => {
    // Step 1: Create account
    await page.goto('/');
    const timestamp = Date.now();
    const companyName = `AI Test Co ${timestamp}`;
    const userEmail = `aitest${timestamp}@example.com`;

    await page.click('button:has-text("Se connecter")');
    await page.click('button:has-text("Créer un compte")');

    // Fill company info
    await page.getByLabel("Nom de l'entreprise").fill(companyName);
    await page.getByRole('combobox').first().click();
    await page.getByRole('option', { name: 'France' }).click();
    await page.getByLabel('Secteur').fill('Restaurant');

    // Fill user info
    await page.getByLabel('Prénom').fill('Test');
    await page.getByLabel('Nom', { exact: true }).fill('Manager');
    await page.getByLabel('Email professionnel').fill(userEmail);
    await page.getByRole('combobox').nth(1).click();
    await page.getByRole('option', { name: 'Administrateur' }).click();
    await page.getByPlaceholder('••••••••').first().fill('TestPassword123!');
    await page.getByPlaceholder('••••••••').nth(1).fill('TestPassword123!');

    await page.click('button:has-text("Créer mon compte")');
    await page.waitForURL(/\/(onboarding|dashboard)/, { timeout: 15000 });

    // Step 2: Navigate to employees and create some test employees
    await page.goto('/employees');
    await page.waitForTimeout(2000);

    // Create Employee 1 - Full-time Waiter
    await page.click('button:has-text("Ajouter un employé")');
    await page.waitForTimeout(1000);
    await page.getByLabel('Prénom').fill('Marie');
    await page.getByLabel('Nom', { exact: true }).fill('Dubois');
    await page.getByLabel('Email').fill(`marie.dubois.${timestamp}@example.com`);
    await page.getByLabel('Type de contrat').click();
    await page.getByRole('option', { name: 'Temps plein' }).click();
    await page.getByLabel('Heures par semaine').fill('35');
    await page.getByLabel('Poste').fill('Serveur');
    await page.getByLabel('Département').fill('Salle');
    await page.click('button:has-text("Créer l\'employé")');
    await page.waitForTimeout(2000);

    // Create Employee 2 - Part-time Cook
    await page.click('button:has-text("Ajouter un employé")');
    await page.waitForTimeout(1000);
    await page.getByLabel('Prénom').fill('Jean');
    await page.getByLabel('Nom', { exact: true }).fill('Martin');
    await page.getByLabel('Email').fill(`jean.martin.${timestamp}@example.com`);
    await page.getByLabel('Type de contrat').click();
    await page.getByRole('option', { name: 'Temps partiel' }).click();
    await page.getByLabel('Heures par semaine').fill('20');
    await page.getByLabel('Poste').fill('Cuisinier');
    await page.getByLabel('Département').fill('Cuisine');
    await page.click('button:has-text("Créer l\'employé")');
    await page.waitForTimeout(2000);

    // Step 3: Navigate to schedules page
    await page.goto('/schedules');
    await page.waitForTimeout(2000);

    // Step 4: Create a new schedule with AI
    await page.click('button:has-text("Nouveau planning")');
    await page.waitForTimeout(1000);

    // Fill schedule form
    await page.getByLabel('Nom du planning').fill(`Planning Test AI ${timestamp}`);
    await page.getByLabel('Description').fill('Generated by AI E2E test');

    // Select date range (next week)
    const today = new Date();
    const nextWeek = new Date(today);
    nextWeek.setDate(today.getDate() + 7);
    const startDate = nextWeek.toISOString().split('T')[0]; // YYYY-MM-DD

    const endOfNextWeek = new Date(nextWeek);
    endOfNextWeek.setDate(nextWeek.getDate() + 6);
    const endDate = endOfNextWeek.toISOString().split('T')[0];

    await page.getByLabel('Date de début').fill(startDate);
    await page.getByLabel('Date de fin').fill(endDate);

    // Step 5: Trigger AI generation
    console.log('🤖 Triggering AI schedule generation...');
    await page.click('button:has-text("Générer avec IA")');

    // Wait for AI generation (could take 5-20 seconds)
    console.log('⏳ Waiting for AI to generate schedule...');
    await page.waitForTimeout(30000); // 30 seconds max for AI response

    // Step 6: Verify success
    // Check for success message or redirect
    await page.waitForTimeout(2000);

    const url = page.url();
    console.log('Current URL after generation:', url);

    // Should either:
    // 1. Show success message on schedules page
    // 2. Redirect to schedule detail page
    // 3. Show schedule in list
    const hasSuccess = await page.locator('text=/Planning créé|Succès|Schedule created/i').count() > 0;
    const hasScheduleInList = await page.locator(`text=/Planning Test AI ${timestamp}/i`).count() > 0;

    console.log('Has success message:', hasSuccess);
    console.log('Has schedule in list:', hasScheduleInList);

    // Verify the schedule was created
    expect(hasSuccess || hasScheduleInList).toBeTruthy();

    console.log('✅ AI Schedule Generation E2E Test Passed!');
  });

  test('should handle AI generation with no employees', async ({ page }) => {
    // Create account without employees
    await page.goto('/');
    const timestamp = Date.now();
    const companyName = `Empty Co ${timestamp}`;
    const userEmail = `empty${timestamp}@example.com`;

    await page.click('button:has-text("Se connecter")');
    await page.click('button:has-text("Créer un compte")');

    await page.getByLabel("Nom de l'entreprise").fill(companyName);
    await page.getByRole('combobox').first().click();
    await page.getByRole('option', { name: 'France' }).click();
    await page.getByLabel('Secteur').fill('Technology');
    await page.getByLabel('Prénom').fill('Test');
    await page.getByLabel('Nom', { exact: true }).fill('User');
    await page.getByLabel('Email professionnel').fill(userEmail);
    await page.getByRole('combobox').nth(1).click();
    await page.getByRole('option', { name: 'Administrateur' }).click();
    await page.getByPlaceholder('••••••••').first().fill('TestPassword123!');
    await page.getByPlaceholder('••••••••').nth(1).fill('TestPassword123!');

    await page.click('button:has-text("Créer mon compte")');
    await page.waitForURL(/\/(onboarding|dashboard)/, { timeout: 15000 });

    // Try to generate schedule
    await page.goto('/schedules');
    await page.waitForTimeout(2000);

    await page.click('button:has-text("Nouveau planning")');
    await page.waitForTimeout(1000);

    await page.getByLabel('Nom du planning').fill('Empty Schedule');
    await page.getByLabel('Date de début').fill('2025-11-01');
    await page.getByLabel('Date de fin').fill('2025-11-07');

    await page.click('button:has-text("Générer avec IA")');
    await page.waitForTimeout(3000);

    // Should show error about no employees
    const hasError = await page.locator('text=/No employees|Aucun employé|employees required/i').count() > 0;
    expect(hasError).toBeTruthy();
  });
});
